---
title: "Home"
---

Welcome to Penguins EDA (Exploratory Data Analysis) and Modeling page! Here, we delve into the fascinating world of penguins, exploring the intricate relationships between their physical characteristics, such as size and mass, across different species and sexes. This project leverages the rich dataset provided by the **`palmerpenguins`** package, offering a closer look at these creatures through various statistical and machine learning techniques.

### **Penguin Size and Mass Analysis**

Utilizing the R programming language, we start by examining the average size and mass of penguins by species and sex. This initial analysis provides insights into the natural variations within these captivating creatures, utilizing **`dplyr`** for data manipulation and **`ggplot2`** for visualization. Our exploration includes creating summaries and visual plots that highlight the differences in bill length and body mass among the species.

### **Data and Modeling**

We then load and clean the penguin data, then fit a linear regression model to predict the body mass of penguins based on features like bill length, species, and sex. This part of the project showcases the application of machine learning techniques to understand and predict aspects of the natural world.

### **Tools and Technologies**

Throughout this exploration, we use a variety of tools and libraries, including:

-   **R Libraries**: **`palmerpenguins`**, **`dplyr`**, **`ggplot2`**, **`DBI`**, **`duckdb`**, **`dbplyr`**, **`httr2`**, and **`rmarkdown`** for data analysis, visualization, and reporting.

-   **Python Libraries**: **`pandas`**, **`numpy`**, **`sklearn`** for data manipulation and machine learning, along with **`vetiver`** and **`pins`** for model deployment and versioning.

-   **Database and API Integration**: Demonstrations of integrating with a DuckDB database and utilizing APIs for model predictions.
