---
title: "Penguins EDA"
format:
  html:
    code-fold: true
---

## Penguin Size and Mass by Sex and Species

```{r}
# install.packages("paws")

library(palmerpenguins)
library(dplyr)
library(ggplot2)
library(DBI)
library(duckdb)
library(dbplyr)
library(httr2)
library(rmarkdown)
library(aws.s3)

df <- palmerpenguins::penguins
```

```{r}
# Set AWS security credentials globally.
Sys.setenv(
    AWS_ACCESS_KEY_ID = "AKIAXYKJWTM4BOYN4UYW",
    AWS_SECRET_ACCESS_KEY = "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",
    AWS_REGION = "us-east-2"
)
```

```{r}
# Create an S3 client, then list the objects within bucket
s3 <- paws::s3()
s3$list_objects(Bucket = "do4ds-lab-brzusek")
```

```{r}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
      where(is.numeric), 
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  knitr::kable()
```

## Penguin Size vs Mass by Species


```{r}
df %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
# Load the Data

#con <- DBI::dbConnect(duckdb::duckdb(), dbdir = #"my-db.duckdb")
#DBI::dbWriteTable(con, "penguins", #palmerpenguins::penguins)
#DBI::dbDisconnect(con)
```

```{r}
# Use the Database

#con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb")
#df <- dplyr::tbl(con, "penguins")

#DBI::dbDisconnect(con)
```

```{r}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
        ends_with("mm") | ends_with("g"),
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  dplyr::collect() %>%
  knitr::kable()
```

```{r}
#req <- httr2::request("http://127.0.0.1:8080/predict") |>
#  httr2::req_body_json(
#    list(
#      list(
#        "bill_length_mm" = 0,
#        "species_Chinstrap" = FALSE,
#        "species_Gentoo" = FALSE,
#        "sex_male" = FALSE
#      )
#    )
#  ) |>
#  httr2::req_perform()
#res <- httr2::resp_body_json(req)$predict[[1]]
```

