on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          
      ## Install R, {renv}, and the packages for content
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true

      - name: Setup renv and install packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        env:
          RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/all/latest
          
      ## Install rmarkdown package
      - name: Install rmarkdown package
        run: Rscript -e "install.packages('remotes'); remotes::install_cran('rmarkdown')"
       
      ## Install Python and the necessary Python packages from requirements.txt
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt
      
      ## Render and Publish
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          
      ## Give Github Actions S3 credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2